import QRCode from 'qrcode'
import './style.css'

const WA = '254794384496'
const booking = (message) => `https://wa.me/${WA}?text=${encodeURIComponent(message)}`
const generalMessage = 'Hi SAMICH NAIL TECH, I would like to book a nail appointment.'

// Gallery media uploaded from the Samich Gallery collection.
const nailGallery = [
  { type: 'video', video: '/assets/gallery/samgal-1.mp4', style: 'Fresh Set', category: 'soft', alt: 'Fresh nail set by Samich Nail Tech' },
  { type: 'video', video: '/assets/gallery/samgal-2.mp4', style: 'Glossy Finish', category: 'minimal', alt: 'Glossy nail finish by Samich Nail Tech' },
  { type: 'image', image: '/assets/gallery/samgal-4.jpeg', style: 'Pink Set', category: 'bold', alt: 'Pink nail set by Samich Nail Tech' },
  { type: 'video', video: '/assets/gallery/whatsapp-video-1.mp4', style: 'Nail Details', category: 'minimal', alt: 'Close-up nail details by Samich Nail Tech' },
  { type: 'image', image: '/assets/gallery/whatsapp-image-1.jpeg', style: 'Soft Girl', category: 'soft', alt: 'Soft girl nail set by Samich Nail Tech' },
  { type: 'video', video: '/assets/gallery/whatsapp-video-2.mp4', style: 'Pretty Tips', category: 'french', alt: 'Pretty nail tips by Samich Nail Tech' },
  { type: 'image', image: '/assets/gallery/whatsapp-image-2.jpeg', style: 'Clean Girl', category: 'minimal', alt: 'Clean girl nail set by Samich Nail Tech' },
  { type: 'video', video: '/assets/gallery/whatsapp-video-3.mp4', style: 'Custom Set', category: 'bold', alt: 'Custom nail set by Samich Nail Tech' },
  { type: 'image', image: '/assets/gallery/whatsapp-image-3.jpeg', style: 'Glossy Nude', category: 'minimal', alt: 'Glossy nude nail set by Samich Nail Tech' },
  { type: 'image', image: '/assets/gallery/whatsapp-image-4.jpeg', style: 'French Tips', category: 'french', alt: 'French tip nail set by Samich Nail Tech' },
  { type: 'image', image: '/assets/gallery/whatsapp-image-5.jpeg', style: 'Bold Art', category: 'bold', alt: 'Bold nail art set by Samich Nail Tech' },
  { type: 'image', image: '/assets/gallery/whatsapp-image-6.jpeg', style: 'Pretty Hands', category: 'soft', alt: 'Pretty hands with a fresh nail set' },
]

const icon = (name) => ({
  arrow: '<span aria-hidden="true">↗</span>', heart: '<span aria-hidden="true">♡</span>', spark: '<span aria-hidden="true">✦</span>', check: '<span aria-hidden="true">✓</span>', pin: '<span aria-hidden="true">⌖</span>', whatsapp: '<svg class="whatsapp-icon" aria-hidden="true" viewBox="0 0 24 24" fill="currentColor"><path d="M20.52 3.48A11.8 11.8 0 0 0 12.06 0C5.5 0 .16 5.34.16 11.9c0 2.1.55 4.15 1.59 5.96L.06 24l6.28-1.65a11.9 11.9 0 0 0 5.72 1.46h.01c6.56 0 11.9-5.34 11.9-11.9 0-3.18-1.24-6.17-3.45-8.43ZM12.07 21.8h-.01a9.9 9.9 0 0 1-5.05-1.38l-.36-.21-3.73.98.99-3.64-.23-.37a9.87 9.87 0 0 1-1.52-5.28C2.16 6.44 6.6 2 12.06 2c2.64 0 5.12 1.03 6.98 2.9a9.8 9.8 0 0 1 2.88 6.99c0 5.46-4.44 9.9-9.85 9.91Zm5.43-7.42c-.3-.15-1.76-.87-2.03-.97-.27-.1-.47-.15-.67.15-.2.3-.77.97-.94 1.17-.17.2-.35.22-.65.07-.3-.15-1.25-.46-2.38-1.47-.88-.78-1.47-1.75-1.64-2.05-.17-.3-.02-.46.13-.61.14-.14.3-.35.45-.52.15-.17.2-.3.3-.5.1-.2.05-.37-.02-.52-.07-.15-.67-1.61-.92-2.2-.24-.58-.49-.5-.67-.51h-.57c-.2 0-.52.07-.79.37-.27.3-1.04 1.02-1.04 2.48 0 1.46 1.06 2.87 1.2 3.07.15.2 2.08 3.17 5.04 4.44.7.3 1.25.48 1.68.62.71.23 1.36.2 1.87.12.57-.08 1.76-.72 2.01-1.41.25-.69.25-1.28.17-1.41-.07-.12-.27-.2-.57-.35Z"/></svg>'
}[name] || '')

const galleryMarkup = (items) => items.map((item, i) => `<button class="gallery-item ${i === 0 ? 'gallery-item--tall' : ''}" data-index="${nailGallery.indexOf(item)}" aria-label="View ${item.style} nail set">${item.type === 'video' ? `<video src="${item.video}" muted loop autoplay playsinline preload="metadata" aria-label="${item.alt}"></video><b class="video-badge" aria-hidden="true">▶</b>` : `<img src="${item.image}" alt="${item.alt}" loading="lazy" width="716" height="890">`}<span>${item.style}</span></button>`).join('')

document.querySelector('#app').innerHTML = `
  <header class="site-header"><a class="wordmark" href="#home" aria-label="SAMICH NAIL TECH home"><span>SAMICH</span><small>NAIL TECH</small></a><nav aria-label="Main navigation"><a href="#home">Home</a><a href="#services">Services</a><a href="#gallery">Gallery</a><a href="#house-calls">House Calls</a><a href="#contact">Contact</a></nav><a class="button button--small" href="${booking(generalMessage)}" target="_blank" rel="noreferrer">Book now ${icon('arrow')}</a><button class="menu-toggle" aria-label="Open menu" aria-expanded="false">☰</button></header>
  <main>
    <section class="hero" id="home"><div class="hero-copy"><p class="eyebrow">NAILS, YOUR WAY <span>${icon('spark')}</span></p><h1>Make a<br><em>statement.</em></h1><p class="hero-tagline">Nails that match your vibe.</p><p class="hero-sub">Fresh sets, pretty hands, and affordable glam — brought directly to you.</p><div class="hero-actions"><a class="button" href="${booking(generalMessage)}" target="_blank" rel="noreferrer">Book on WhatsApp ${icon('arrow')}</a><a class="text-link" href="#gallery">View my work <span>↓</span></a></div><div class="price-tease"><span>Gel <b>Ksh 250</b></span><i></i><span>Tips + Gel <b>from Ksh 500</b></span></div></div><div class="hero-art"><div class="art-orbit"></div><div class="image-frame"><img src="/assets/samich-nails-editorial.png" alt="Glossy blush gel manicure by SAMICH NAIL TECH" width="716" height="890"></div><span class="art-note">pretty<br>hands,<br>always.</span><span class="art-star">✦</span></div></section>
    <section class="ticker" aria-label="Service highlights"><span>HOUSE CALLS</span><span>✦</span><span>GEL FROM KSH 250</span><span>✦</span><span>NAILS THAT MATCH YOUR VIBE</span><span>✦</span><span>HOUSE CALLS</span></section>
    <section class="section featured" id="work"><div class="section-heading"><div><p class="eyebrow">A LITTLE INSPO</p><h2>Fresh sets for<br><em>every mood.</em></h2></div><p>From clean and glossy to cute and extra — bring the inspo, I’ll bring the polish.</p></div><div class="featured-grid">${galleryMarkup(nailGallery.slice(0, 4))}</div></section>
    <section class="section services" id="services"><div class="section-heading"><div><p class="eyebrow">KEEPING IT CUTE</p><h2>Good nails.<br><em>Good price.</em></h2></div><p>Affordable glam, without the salon trip. Choose your set and let’s get you booked.</p></div><div class="service-grid"><article class="service-card"><div class="service-top"><span class="service-number">01</span><span class="service-icon">${icon('spark')}</span></div><h3>Gel</h3><p>Clean, glossy colour for a simple, polished look.</p><div class="service-bottom"><strong>Ksh <b>250</b></strong><a class="button button--dark" href="${booking('Hi SAMICH NAIL TECH, I would like to book Gel nails at Ksh 250.')}" target="_blank" rel="noreferrer">Book Gel ${icon('arrow')}</a></div></article><article class="service-card service-card--rose"><div class="service-top"><span class="service-number">02</span><span class="service-icon">${icon('heart')}</span></div><h3>Tips + Gel</h3><p>Add length, shape and your favourite gel finish.</p><div class="service-bottom"><strong>From Ksh <b>500</b></strong><a class="button button--dark" href="${booking('Hi SAMICH NAIL TECH, I would like to book Tips and Gel.')}" target="_blank" rel="noreferrer">Book Tips + Gel ${icon('arrow')}</a></div></article></div></section>
    <section class="section vibe" id="gallery"><div class="section-heading"><div><p class="eyebrow">YOUR ENERGY, ON YOUR TIPS</p><h2>Choose your<br><em>nail vibe.</em></h2></div><p>Tap a mood to find a set that feels like you.</p></div><div class="filters" role="group" aria-label="Filter nail styles"><button class="filter active" data-filter="all">All sets</button><button class="filter" data-filter="soft">Soft girl</button><button class="filter" data-filter="french">French tips</button><button class="filter" data-filter="minimal">Minimal</button><button class="filter" data-filter="bold">Bold</button></div><div class="gallery-grid" id="gallery-grid">${galleryMarkup(nailGallery)}</div></section>
    <section class="house-calls" id="house-calls"><div class="house-copy"><p class="eyebrow">THE BEST PART?</p><h2>Beauty comes<br><em>to you.</em></h2><p>No salon trip needed. I bring your nail appointment to campus, hostels, home, or your preferred location.</p><a class="button button--light" href="${booking('Hi SAMICH NAIL TECH, I would like to book a house call. My preferred location is: ')}" target="_blank" rel="noreferrer">Book a house call ${icon('arrow')}</a></div><div class="house-photo"><img src="/assets/house-call.png" alt="Nail technician applying gel polish during a house call" loading="lazy" width="1200" height="800"></div><div class="location-pills"><span>${icon('pin')} Campus</span><span>${icon('pin')} Hostels</span><span>${icon('pin')} Home</span><span>${icon('pin')} Your spot</span></div></section>
    <section class="section why"><div class="section-heading"><div><p class="eyebrow">WHY SAMICH?</p><h2>Small details.<br><em>Big energy.</em></h2></div></div><div class="benefits"><article><span>01</span><h3>Hygiene first</h3><p>Clean tools and careful service, every time.</p></article><article><span>02</span><h3>Student friendly</h3><p>Affordable prices designed with you in mind.</p></article><article><span>03</span><h3>Flexible booking</h3><p>Arrange a time and place that works for you.</p></article><article><span>04</span><h3>Custom styles</h3><p>Bring your inspo or dream up something unique.</p></article></div></section>
    <section class="section booking-steps"><div class="section-heading"><div><p class="eyebrow">NO STRESS, JUST SETS</p><h2>Booking is<br><em>easy.</em></h2></div><p>One quick WhatsApp message and your next set is in motion.</p></div><div class="steps"><article><b>1</b><h3>Choose your style</h3><p>Pick a vibe or bring your inspo.</p></article><article><b>2</b><h3>Message on WhatsApp</h3><p>Tell me what you’re feeling.</p></article><article><b>3</b><h3>Confirm your details</h3><p>Set a time and location.</p></article><article><b>4</b><h3>Get your nails done</h3><p>Show up cute. Leave glowing.</p></article></div></section>
    <section class="final-cta" id="contact"><div><p class="eyebrow">READY WHEN YOU ARE <span>${icon('spark')}</span></p><h2>Your next set<br>starts <em>here.</em></h2><p>Gel from Ksh 250 · Tips + Gel from Ksh 500 · House calls available</p></div><a class="button button--light" href="${booking(generalMessage)}" target="_blank" rel="noreferrer">Book on WhatsApp ${icon('arrow')}</a></section>
  </main>
  <footer><div class="footer-brand"><a class="wordmark" href="#home"><span>SAMICH</span><small>NAIL TECH</small></a><p>Nails that match your vibe.</p></div><div class="footer-links"><div><strong>Explore</strong><a href="#services">Services</a><a href="#gallery">Gallery</a><a href="#house-calls">House calls</a></div><div><strong>Book</strong><a href="${booking(generalMessage)}" target="_blank" rel="noreferrer">WhatsApp</a><a href="tel:0794384496">0794 384 496</a><span>House calls only</span></div></div><div class="qr-wrap"><canvas id="qr" width="100" height="100" aria-label="QR code to book on WhatsApp"></canvas><span>Scan to book</span></div><div class="footer-bottom"><span>© ${new Date().getFullYear()} SAMICH NAIL TECH. All rights reserved.</span><span>Made for pretty hands ${icon('heart')}</span></div></footer>
  <a class="floating-wa" href="${booking(generalMessage)}" target="_blank" rel="noreferrer" aria-label="Book on WhatsApp">${icon('whatsapp')}<span>Book on WhatsApp</span></a>
  <div class="lightbox" role="dialog" aria-modal="true" aria-label="Nail work preview" hidden><button class="lightbox-close" aria-label="Close preview">×</button><div class="lightbox-media"></div><p></p></div>
`

const renderGallery = (filter = 'all') => { const items = filter === 'all' ? nailGallery : nailGallery.filter(x => x.category === filter); document.querySelector('#gallery-grid').innerHTML = galleryMarkup(items) }
document.addEventListener('click', (e) => {
  const filter = e.target.closest('.filter'); if (filter) { document.querySelectorAll('.filter').forEach(x => x.classList.remove('active')); filter.classList.add('active'); renderGallery(filter.dataset.filter) }
  const item = e.target.closest('.gallery-item'); if (item) { const data = nailGallery[Number(item.dataset.index)]; const box = document.querySelector('.lightbox'); const media = box.querySelector('.lightbox-media'); media.innerHTML = data.type === 'video' ? `<video src="${data.video}" controls autoplay playsinline></video>` : `<img src="${data.image}" alt="${data.alt}">`; box.querySelector('p').textContent = data.style; box.hidden = false; document.body.classList.add('modal-open'); box.querySelector('.lightbox-close').focus() }
  if (e.target.closest('.lightbox-close') || (e.target.classList.contains('lightbox'))) { document.querySelector('.lightbox').hidden = true; document.body.classList.remove('modal-open') }
  const menu = e.target.closest('.menu-toggle'); if (menu) { const nav = document.querySelector('nav'); const open = nav.classList.toggle('open'); menu.setAttribute('aria-expanded', open) }
})
document.addEventListener('keydown', e => { if (e.key === 'Escape') { document.querySelector('.lightbox').hidden = true; document.body.classList.remove('modal-open') } })
QRCode.toCanvas(document.querySelector('#qr'), booking(generalMessage), { width: 100, margin: 1, color: { dark: '#1e1b1b', light: '#fffaf6' } })
